import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shared/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative">
          <div className="flex">
            <Sidebar />
            <section className="flex bg-gray min-h-screen flex-1 flex-col px-14 py-11">
              <div className="mx-auto w-full max-w-5xl">{children}</div>
            </section>
          </div>
        </main>
      </body>
    </html>
  );
}
